version: "3"

services:
  # Mysql (5.7)
  mysql:
    container_name: "${PROJECT_NAME}-mysql"
    build:
      context: ./
      dockerfile: ./docker/mysql/Dockerfile
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    restart: "always"
    ports:
      - "${DB_PORT}:3306"
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=${DB_ALLOW_EMPTY_PASSWORD}
    networks:
      - app-network

  # PHP (7.3.5-fpm-alpine3.9)
  php:
    container_name: "${PROJECT_NAME}-php"
    build:
      context: ./docker/php
    volumes:
      - ./:/app
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    restart: "always"
    networks:
      - app-network

  # Nginx (1.16.0-alpine)
  nginx:
    container_name: "${PROJECT_NAME}-nginx"
    build:
      context: ./docker/nginx
    tty: true
    environment:
      SERVICE_NAME: ${PROJECT_NAME}-nginx
      SERVICE_TAGS: dev
    working_dir: /app
    restart: "always"
    volumes:
      - ./:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${NGINX_PORT}:80"
    links:
      - "php"
      - "mysql"
    networks:
      - app-network

# Docker Networks
networks:
  app-network:
    driver: bridge
